version: '3.1'

services:
  api:
    image: hinge-api
    ports:
      - 8000:8000
  postgres:
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    volumes:
      - ./db/hinge.sql:/docker-entrypoint-initdb.d/hinge.sql
    environment: 
      POSTGRES_PASSWORD: password
      